image:
  - Visual Studio 2019

environment:

  global:
    BOOST_ROOT: "C:\\Libraries\\boost_1_77_0"
    PIP_PASSWORD:
      secure: 5/+VoitJX0FZVcCLi1xOHQ==

  matrix:
    - PYTHON: "C:\\Python39-x64"

install:
  - cmd: "%PYTHON%\\python.exe get_external.py"
  - cmd: SET EIGEN_ROOT=%CD%\eigen-3.4.0-3147391d946bb4b6c68edd901f2add6ac1f31f8c
  - cmd: "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - cmd: "%PYTHON%\\python.exe -m pip install -r requirements_docs.txt"
  # We need wheel installed to build wheels later
  - cmd: "%PYTHON%\\python.exe -m pip install wheel"
  - cmd: "%PYTHON%\\python.exe -m pip freeze > used_packages.txt"
  - cmd: "%PYTHON%\\python.exe setup.py install"

build: off

test_script:
  - cmd: mkdir testrundir
  - cmd: cd testrundir
  - cmd: "%PYTHON%\\scripts\\py.test --pyargs pysim"
  - cmd: cd..

after_test:
  - cmd: "%PYTHON%\\python.exe setup.py bdist_wheel"
  - cmd: "%PYTHON%\\python.exe setup.py build_sphinx"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
  - path: used_packages.txt
  - path: build\sphinx\html

