name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python-version: ['3.9']
        os: ['macos-11']
    name: Python ${{ matrix.python-version }} test
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install c++ dependendencies
        if: ${{matrix.os == 'macos-11'}}
        run: | 
          brew install eigen
          brew install boost

      - run: pip install wheel
      - run: pip install -r requirements.txt
      - run: python setup.py build_ext --inplace
