name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python-version: ['3.9', '3.8']
        os: ['macos-11', 'ubuntu-20.04']
    name: Python ${{ matrix.python-version }} test on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install c++ dependendencies on mac
        if: ${{matrix.os == 'macos-11'}}
        run: | 
          brew install eigen
          brew install boost

      - name: Install c++ dependendencies on ubuntu
        if: ${{matrix.os == 'ubuntu-20.04'}}
        run: | 
          sudo apt-get install libeigen3-dev
          sudo apt-get install -y libboost-all-dev

      - name: Install Python dependencies
        run: | 
          pip install wheel
          pip install -r requirements.txt
      - name: Build c++ extensions inplace
        run: python setup.py build_ext --inplace
      - name: Run Tests
        run: pytest
