name: Tests

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    strategy:
      matrix:
        python-version: ['3.9', '3.8', '3.7']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install c++ dependendencies
        run: | 
          brew install eigen
          brew install boost

      - name: Install Python dependencies
        run: | 
          pip install wheel
          pip install -r requirements.txt

      - name: Build c++ extensions inplace
        run: python setup.py build_ext --inplace

      - name: Run Tests
        run: pytest

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Archive wheel
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/*
        
  publish:
    runs-on: 'ubuntu-20.04'
    needs: build

    steps:

      - uses: actions/checkout@v2

      - name: Build source dist
        run: | 
          pip3 install -r requirements.txt
          python3 setup.py sdist

      - name: Download wheels
        uses: actions/download-artifact@v2
        with:
          name: wheel
          path: dist

      - name: Build manylinux wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2014_x86_64
        with:
          python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39'
          build-requirements: 'cython numpy'
          system-packages: 'eigen3-devel boost boost-devel'

      - name: Remove non-manylinux wheels
        run: rm ./dist/*-linux_*
   
      - name: Archive dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
